
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ajay
 */
public class CheckExpiry extends javax.swing.JFrame {

    /**
     * Creates new form CheckExpiry
     */
    DefaultTableModel model;

    public CheckExpiry() {
        initComponents();
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        FindExpiry();
    }

    public void FindExpiry() {
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            String Driver = "com.mysql.jdbc.Driver";
            Class.forName(Driver);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MSAS", "root", "");
            String sql = "select *from Medicine";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                Date date = rs.getDate("Exp_Date");
                String str = date.toString();

                String dt[] = str.split("-", 4);

                int year = Integer.parseInt(dt[0]);
                int month = Integer.parseInt(dt[1]);
                int day = Integer.parseInt(dt[2]);

                SimpleDateFormat obj = new SimpleDateFormat("YYYY-MM-dd");
                java.util.Date cu = new java.util.Date();
                String current = obj.format(cu);

                String cur[] = current.split("-", 4);
                int year1 = Integer.parseInt(cur[0]);
                int month1 = Integer.parseInt(cur[1]);
                int day1 = Integer.parseInt(cur[2]);
                int expiry = 0;
                if (year < year1) {
                    expiry = 1;
                } else if (year == year1) {
                    if (month < month1) {
                        expiry = 1;
                    } else if (month == month1) {
                        if (day <= day1) {
                            expiry = 1;
                        }
                    }
                }
                if (expiry == 1) {
                    String name = rs.getString("Name");
                    Date d = rs.getDate("Exp_Date");
                    int mid = rs.getInt("MID");
                    double price = rs.getDouble("Price");
                    int qnty = rs.getInt("Qnty");
                    Object obj1[] = {name, d, price, qnty};
                    if(start == 0){
                        MID[index] = mid;
                        index++;
                        System.out.println(MID[index - 1]);
                    }
                    model.addRow(obj1);
                }
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        remove = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        remove_medicine = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        jLabel1.setText("Expired Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 25, 234, 41));

        jTable1.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Expiry_Date", "Cost", "No.Items"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 490, 293));

        remove.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        remove.setText("Delete Medicine");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, 80));

        remove_medicine.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        remove_medicine.setForeground(new java.awt.Color(233, 42, 42));
        getContentPane().add(remove_medicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 420, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        try {
            String Driver = "com.mysql.jdbc.Driver";
            Class.forName(Driver);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MSAS", "root", "");
            int i = 0;
            while (i < index) {
                int mid = MID[i];
                String sql = "Delete from Medicine where MID = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setInt(1,mid);
                int nr = stmt.executeUpdate();
                if(nr != 0)
                    remove_medicine.setText("Succussfully Expired Medicine removed");
                else
                    remove_medicine.setText("Something went Wrong");
                i++;
                
            }
            FindExpiry();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_removeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static int MID[] = new int[1000];
    public static int index = 0,start=0;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckExpiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckExpiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckExpiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckExpiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckExpiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton remove;
    private javax.swing.JLabel remove_medicine;
    // End of variables declaration//GEN-END:variables
}
